version: "3"

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local

services:
  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USERNAME=ivan
      - MARIADB_PASSWORD=ivan
      - MARIADB_DATABASE=forecast
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup
    networks:
      - default

  v1:
    build: /tmp/workflow/servicev1/
    command: gunicorn apiv1:app -b 0.0.0.0:8000
    environment:
      - HOST=db
    ports:
      - 8000:8000
    links:
      - db

  v2:
    build: /tmp/workflow/servicev2/
    command: gunicorn apiv2:app -b 0.0.0.0:8001
    environment:
      - API_KEY=9BE5Q3qhA5z9aR5Ncza7B6c4boUMXAZR
    ports:
      - 8001:8001
